using WinterRose.ImGuiUI.Win32;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WinterRose.ImGuiApps
{
    internal static class InputHelper
    {
        public static Dictionary<Key, WinKey> CreateKeyMap()
        {
            var keyMap = new Dictionary<Key, WinKey>
            {
                { Key.LeftMouseButton, WinKey.LBUTTON },
                { Key.RightMouseButton, WinKey.RBUTTON },
                { Key.Cancel, WinKey.CANCEL },
                { Key.MiddleMouseButton, WinKey.MBUTTON },
                { Key.XButton1, WinKey.XBUTTON1 },
                { Key.XButton2, WinKey.XBUTTON2 },
                { Key.Backspace, WinKey.BACK },
                { Key.Tab, WinKey.TAB },
                { Key.Clear, WinKey.CLEAR },
                { Key.Return, WinKey.RETURN },
                { Key.Shift, WinKey.SHIFT },
                { Key.Control, WinKey.CONTROL },
                { Key.Alt, WinKey.MENU },
                { Key.Pause, WinKey.PAUSE },
                { Key.CapsLock, WinKey.CAPITAL },
                { Key.Escape, WinKey.ESCAPE },
                { Key.Convert, WinKey.CONVERT },
                { Key.NonConvert, WinKey.NONCONVERT },
                { Key.Accept, WinKey.ACCEPT },
                { Key.ModeChange, WinKey.MODECHANGE },
                { Key.Space, WinKey.SPACE },
                { Key.PageUp, WinKey.PRIOR },
                { Key.PageDown, WinKey.NEXT },
                { Key.End, WinKey.END },
                { Key.Home, WinKey.HOME },
                { Key.LeftArrow, WinKey.LEFT },
                { Key.UpArrow, WinKey.UP },
                { Key.RightArrow, WinKey.RIGHT },
                { Key.DownArrow, WinKey.DOWN },
                { Key.Select, WinKey.SELECT },
                { Key.Print, WinKey.PRINT },
                { Key.Execute, WinKey.EXECUTE },
                { Key.PrintScreen, WinKey.SNAPSHOT },
                { Key.Insert, WinKey.INSERT },
                { Key.Delete, WinKey.DELETE },
                { Key.Help, WinKey.HELP },
                { Key.n0, WinKey.KEY_0 },
                { Key.n1, WinKey.KEY_1 },
                { Key.n2, WinKey.KEY_2 },
                { Key.n3, WinKey.KEY_3 },
                { Key.n4, WinKey.KEY_4 },
                { Key.n5, WinKey.KEY_5 },
                { Key.n6, WinKey.KEY_6 },
                { Key.n7, WinKey.KEY_7 },
                { Key.n8, WinKey.KEY_8 },
                { Key.n9, WinKey.KEY_9 },
                { Key.A, WinKey.KEY_A },
                { Key.B, WinKey.KEY_B },
                { Key.C, WinKey.KEY_C },
                { Key.D, WinKey.KEY_D },
                { Key.E, WinKey.KEY_E },
                { Key.F, WinKey.KEY_F },
                { Key.G, WinKey.KEY_G },
                { Key.H, WinKey.KEY_H },
                { Key.I, WinKey.KEY_I },
                { Key.J, WinKey.KEY_J },
                { Key.K, WinKey.KEY_K },
                { Key.L, WinKey.KEY_L },
                { Key.M, WinKey.KEY_M },
                { Key.N, WinKey.KEY_N },
                { Key.O, WinKey.KEY_O },
                { Key.P, WinKey.KEY_P },
                { Key.Q, WinKey.KEY_Q },
                { Key.R, WinKey.KEY_R },
                { Key.S, WinKey.KEY_S },
                { Key.T, WinKey.KEY_T },
                { Key.U, WinKey.KEY_U },
                { Key.V, WinKey.KEY_V },
                { Key.W, WinKey.KEY_W },
                { Key.X, WinKey.KEY_X },
                { Key.Y, WinKey.KEY_Y },
                { Key.Z, WinKey.KEY_Z },
                { Key.LeftWindows, WinKey.LWIN },
                { Key.RightWindows, WinKey.RWIN },
                { Key.Apps, WinKey.APPS },
                { Key.Sleep, WinKey.SLEEP },
                { Key.Numpad0, WinKey.NUMPAD0 },
                { Key.Numpad1, WinKey.NUMPAD1 },
                { Key.Numpad2, WinKey.NUMPAD2 },
                { Key.Numpad3, WinKey.NUMPAD3 },
                { Key.Numpad4, WinKey.NUMPAD4 },
                { Key.Numpad5, WinKey.NUMPAD5 },
                { Key.Numpad6, WinKey.NUMPAD6 },
                { Key.Numpad7, WinKey.NUMPAD7 },
                { Key.Numpad8, WinKey.NUMPAD8 },
                { Key.Numpad9, WinKey.NUMPAD9 },
                { Key.Multiply, WinKey.MULTIPLY },
                { Key.Add, WinKey.ADD },
                { Key.Separator, WinKey.SEPARATOR },
                { Key.Subtract, WinKey.SUBTRACT },
                { Key.Decimal, WinKey.DECIMAL },
                { Key.Divide, WinKey.DIVIDE },
                { Key.F1, WinKey.F1 },
                { Key.F2, WinKey.F2 },
                { Key.F3, WinKey.F3 },
                { Key.F4, WinKey.F4 },
                { Key.F5, WinKey.F5 },
                { Key.F6, WinKey.F6 },
                { Key.F7, WinKey.F7 },
                { Key.F8, WinKey.F8 },
                { Key.F9, WinKey.F9 },
                { Key.F10, WinKey.F10 },
                { Key.F11, WinKey.F11 },
                { Key.F12, WinKey.F12 },
                { Key.F13, WinKey.F13 },
                { Key.F14, WinKey.F14 },
                { Key.F15, WinKey.F15 },
                { Key.F16, WinKey.F16 },
                { Key.F17, WinKey.F17 },
                { Key.F18, WinKey.F18 },
                { Key.F19, WinKey.F19 },
                { Key.F20, WinKey.F20 },
                { Key.F21, WinKey.F21 },
                { Key.F22, WinKey.F22 },
                { Key.F23, WinKey.F23 },
                { Key.F24, WinKey.F24 },
                { Key.NumLock, WinKey.NUMLOCK },
                { Key.ScrollLock, WinKey.SCROLL },
                { Key.LeftShift, WinKey.LSHIFT },
                { Key.RightShift, WinKey.RSHIFT },
                { Key.LeftControl, WinKey.LCONTROL },
                { Key.RightControl, WinKey.RCONTROL },
                { Key.LeftAlt, WinKey.LMENU },
                { Key.RightAlt, WinKey.RMENU },
                { Key.BrowserBack, WinKey.BROWSER_BACK },
                { Key.BrowserForward, WinKey.BROWSER_FORWARD },
                { Key.BrowserRefresh, WinKey.BROWSER_REFRESH },
                { Key.BrowserStop, WinKey.BROWSER_STOP },
                { Key.BrowserSearch, WinKey.BROWSER_SEARCH },
                { Key.BrowserFavorites, WinKey.BROWSER_FAVORITES },
                { Key.BrowserHome, WinKey.BROWSER_HOME },
                { Key.VolumeMute, WinKey.VOLUME_MUTE },
                { Key.VolumeDown, WinKey.VOLUME_DOWN },
                { Key.VolumeUp, WinKey.VOLUME_UP },
                { Key.MediaNextTrack, WinKey.MEDIA_NEXT_TRACK },
                { Key.MediaPreviousTrack, WinKey.MEDIA_PREV_TRACK },
                { Key.MediaStop, WinKey.MEDIA_STOP },
                { Key.MediaPlayPause, WinKey.MEDIA_PLAY_PAUSE },
                { Key.LaunchMail, WinKey.LAUNCH_MAIL },
                { Key.SelectMedia, WinKey.LAUNCH_MEDIA_SELECT },
                { Key.LaunchApp1, WinKey.LAUNCH_APP1 },
                { Key.LaunchApp2, WinKey.LAUNCH_APP2 },
                { Key.Semicolon, WinKey.OEM_1 },
                { Key.Plus, WinKey.OEM_PLUS },
                { Key.Comma, WinKey.OEM_COMMA },
                { Key.Minus, WinKey.OEM_MINUS },
                { Key.Period, WinKey.OEM_PERIOD },
                { Key.Slash, WinKey.OEM_2 },
                { Key.Backtick, WinKey.OEM_3 },
                { Key.LeftBracket, WinKey.OEM_4 },
                { Key.Backslash, WinKey.OEM_5 },
                { Key.RightBracket, WinKey.OEM_6 },
                { Key.Apostrophe, WinKey.OEM_7 },
                { Key.OEM_8, WinKey.OEM_8 },
                { Key.OEM_102, WinKey.OEM_102 },
                { Key.ProcessKey, WinKey.PROCESSKEY },
                { Key.Packet, WinKey.PACKET },
                { Key.Attention, WinKey.ATTN },
                { Key.CrSel, WinKey.CRSEL },
                { Key.ExSel, WinKey.EXSEL },
                { Key.EraseEOF, WinKey.EREOF },
                { Key.Play, WinKey.PLAY },
                { Key.Zoom, WinKey.ZOOM },
                { Key.NoName, WinKey.NONAME },
                { Key.PA1, WinKey.PA1 }
            };

            return keyMap;
        }
    }
}
