using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WinterRose.SourceGeneration
{
    /// <summary>
    /// To be used on generated classes, methods, properties, fields, etc. to indicate that they were generated by the source generator.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = false)]
    public class GeneratedAttribute : Attribute
    {
        /// <summary>
        /// The name of the generator that generated the target.
        /// </summary>
        public string GeneratorName { get; }

        ///<summary>
        /// The version of the generator that generated the target.
        /// </summary>
        public string GeneratorVersion { get; }

        /// <summary>
        /// The type on which the generated serializer works on
        /// </summary>
        public string WorkingType { get; }

        ///<summary>
        /// The name of the generator that generated the target.
        /// </summary>
        /// <param name="generatorName">The name of the generator that generated the target.</param>
        /// <param name="generatorVersion">The version of the generator that generated the target.</param>
        /// <param name="argument">An argument that can be used to differentiate why and for what this member was generated</param>
        public GeneratedAttribute(string generatorName, string generatorVersion, string argument)
        {
            GeneratorName = generatorName;
            GeneratorVersion = generatorVersion;
            WorkingType = argument;
        }
    }
}